language: "python"
python:
    - "3.6"

env:
    global:
        - DJANGO_SETTINGS_MODULE=website.settings.dev

services:
    - elasticsearch

install:
    - pip install -r requirements.txt
    - createdb cosio -U postgres -w
    - python manage.py migrate
    # - printf '\n\n' | python manage.py createsuperuser

script:
  - flake8 .
  - py.test
