version: '3'
volumes:
  postgres_data_vol:
    external: false
  elasticsearch_data_vol:
    external: false
services:
  postgres:
    image: postgres:9.6
    command:
      - /bin/bash
      - -c
      - echo "$$POSTGRES_INITDB" > /docker-entrypoint-initdb.d/commands.sh &&
        chmod +x /docker-entrypoint-initdb.d/commands.sh &&
        /docker-entrypoint.sh postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: cosio
    volumes:
      - "${POSTGRES_DATA_VOL:-postgres_data_vol}:/var/lib/postgresql/data/"
  elasticsearch:
    image: elasticsearch:2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data_vol:/usr/share/elasticsearch/data
  redis:
    image: redis:3.2
    ports:
      - 6379:6379
